### PR TITLE
Support shallow cloning

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello & thanks for this tool!

I'd like to test-drive it, but wasn't yet sure how to and where to read up on the functionality.

Still I'd already like to suggest to use shallow cloning, since "locat[ing] typos" probably does not mean a proof-reader routinely needs to dive into a projects commit history. According to [Atlassian](https://www.atlassian.com/git/tutorials/big-repositories) & [Linux Hint](https://linuxhint.com/git-shallow-clone-and-clone-depth/), this both speeds up the cloning process & reduces the amount of locally required storage space for the clone.

- [ ] Unit tests added (haven't had much experience with those in Python, sorry)
- [ ] Documentations updated with the change ([not yet drafted](https://github.com/timgates42/meticulous/tree/e0f31dc07881d8d953a2312ed875ad00d34797f0/docs)?)
- [ ] Towncrier news fragment added (new to me)

I'll add these things, if we generally agree about this change suggestion or how to implement it more elegantly.

Cheers!

### CODE REVIEW

**Comment by timgates42** [comment]
Thanks so much for your contribution @katrinleinweber it's a great idea, I can't wait to give it a try and see if I notice the improved speed. I will make the pull request template a bit friendlier and mention that I'm happy to clean up any pull requests. I see this one is failing the CI black step which is very easy for me to fix up and I'll add the towncrier news.

In terms of trying out this repo - I'll try out your change and publish a new version with your shallow cloning support and then it should be super easy to get going by just running.

python -m pip install meticulous
python -m meticulous

It will then just ask for a GitHub API token to submit PRs for any typo's you fix up. I should also add some instructions on using the program. I'll see if I can get something quick going.

Just a warning it currently ignores the EDITOR environment variable and always uses vim to view the spelling suggestions and make any typo submissions. What editor do you usual use?

**Comment by timgates42** [comment]
I've run black on the files and added a towncrier news fragment in the above commits, I'll merge this once the CI completes.

**Comment by timgates42** [comment]
I'm starting work on a guide on how to use meticulous - you can see my first attempt at https://github.com/timgates42/meticulous/blob/4f0e52a1f1fec183e57a19f0f42311cc1f8fa8b6/docs/index.rst

**Comment by timgates42** [comment]
I published 0.9.1 with your changes @katrinleinweber and my initial guide is online now at https://meticulous.readthedocs.io/en/latest/ let me know how you go and if you have any suggestions to make the documentation easier for others to try it out. - Thanks

**Comment by katrinleinweber** [comment]
Thanks for finalising this :-)

> What editor do you usual use?

Sublime Text 3

**Pull request merged**
